import './globals.css'
import Link from 'next/link'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body> 
        <nav>
          <Link href="/about">About</Link>
          <h1>Home</h1>
          <h1>About</h1>
          <h1>Work</h1>
          <h1>Resume</h1>
          <h1>Contact</h1>
          <h1>Blog</h1>
        </nav>
        {children}
        </body>
    </html>
  )
}
